version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run export
  post_build:
    commands:
      # copy the contents of ./app/out to S3
      - aws s3 cp --recursive --acl public-read app/out s3://gulls-spacex/       
      # set the cache-control headers for index.html to prevent      
      - >
        aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        app/out/index.html s3://gulls-spacex/ 
